### ISSUE TITLE
Running GMD in docker with KVM

### ISSUE THREAD

**Issue by warting** [siarhei-luskanau/android-managed-virtual-device#1]
Hi!

Looks like you have made a great effort exploring gradle managed devices in github. I was wondering if you have some experience getting the same thing up and running on a self hosted docker machine supporting KVM?

I have a sample project here trying to make it work

https://github.com/warting/gradle-managed-devices-docker

The error I receive is:
```
Caused by: java.lang.IllegalStateException: Gradle was not able to complete device setup for: dev30_google_apis_x86_Nexus_4
The emulator failed to open the managed device to generate the snapshot.
This is because the emulator closed unexpectedly, try updating the emulator and
ensure a device can be run from Android Studio.
        at com.android.build.gradle.internal.AvdSnapshotHandler.generateSnapshot(AvdSnapshotHandler.kt:264)
        at com.android.build.gradle.internal.AvdManager$loadSnapshotIfNeeded$1.invoke(AvdManager.kt:214)
        at com.android.build.gradle.internal.AvdManager$loadSnapshotIfNeeded$1.invoke(AvdManager.kt:194)
        at com.android.build.gradle.internal.AvdManager$runWithMultiProcessLocking$1.accept(AvdManager.kt:113)
        at com.android.build.gradle.internal.AvdManager$runWithMultiProcessLocking$1.accept(AvdManager.kt:113)
        at com.android.builder.utils.SynchronizedFile.doActionWithMultiProcessLocking(SynchronizedFile.java:273)
        ... 35 more
```

**Comment by siarhei-luskanau** [comment]
Hi!

I have tried to use self hosted runners. Please see the documentations [About self-hosted runners](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners).

I have no experience with docker machine. How do you want to use docker machine and what result do you want achieve?

**Comment by warting** [comment]
Hey, the problem is not that it is docker or self hosted runners. The problem is running the android emulators in nested virtualisated environments. Docker machine is just one common way of creating them :)

**Comment by siarhei-luskanau** [comment]
@warting Looks like now we can run android emulators in Ubuntu runners. We can enable the nested virtualization

```      - name: Enable KVM group perms
        if: contains(matrix.os, 'ubuntu')
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

```
